version: '3.8'

services:
  web:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    command: ["bash", "-c", "pip install flask && python /app/app.py"]

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: examplepassword

