version: '3.8'

services:
  web:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    volumes:
      - ./app:/server.py
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: examplepassword

