FROM python:latest

ADD /home/rooshan/Desktop/Lab_Final_2022506/Q2/CS205L_Final/PythonFiles/server/docker-compose/app/server.py /

WORKDIR /home/rooshan/Desktop/Lab_Final_2022506/Q2/CS205L_Final/PythonFiles/server

CMD ["python", "server.py"]
